// Default MMIO base addresses for the RIVET Ethernet block.

#ifndef SOFTWARE_ETHERNET_MMIO_CONFIG_H_
#define SOFTWARE_ETHERNET_MMIO_CONFIG_H_

#define ETHERNET_TX_BASE 0x2000UL

#define ETHERNET_RX_BASE 0x2400UL

#define ETHERNET_CSR_BASE 0x2800UL

#define ETHERNET_MDIO_BASE 0x2900UL

#endif  // SOFTWARE_ETHERNET_MMIO_CONFIG_H_
